### ISSUE TITLE
5070ti运行时报错

### ISSUE THREAD

**Issue by caomyv** [YanWenKun/Hunyuan3D-2-WinPortable#43]
错误信息：
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by YanWenKun** [comment]
用新版试试：
https://github.com/YanWenKun/Hunyuan3D-2-WinPortable/releases/tag/v2

**Comment by STAR-FALL-00** [comment]
新版的按照步骤重新部署还是出现了错误：
error
CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by STAR-FALL-00** [comment]
终端中的日志如下：
Created new folder: gradio_cache\bfbeb7cd-1243-4ddf-9aa3-90e4fa753a54
Traceback (most recent call last):
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\anyio\_backends\_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\Hunyuan3D-2\gradio_app.py", line 324, in shape_generation
    mesh, image, save_folder, stats, seed = _gen_shape(
                                            ^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\Hunyuan3D-2\gradio_app.py", line 219, in _gen_shape
    outputs = i23d_worker(
              ^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\Hunyuan3D-2\hy3dgen\shapegen\pipelines.py", line 714, in __call__
    cond = self.encode_cond(
           ^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\Hunyuan3D-2\hy3dgen\shapegen\utils.py", line 83, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\Hunyuan3D-2\hy3dgen\shapegen\pipelines.py", line 424, in encode_cond
    cond = self.conditioner(image=image, **additional_cond_inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\mmgp\offload.py", line 1924, in check_change_module
    return previous_method(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\Hunyuan3D-2\hy3dgen\shapegen\models\conditioner.py", line 249, in forward
    'main': self.main_image_encoder(image, mask=mask, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\python_standalone\Lib\site-packages\mmgp\offload.py", line 1924, in check_change_module
    return previous_method(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Hunyuan3D2_WinPortable\Hunyuan3D-2\hy3dgen\shapegen\models\conditioner.py", line 157, in forward
    image = (image - low) / (high - low)
             ~~~~~~^~~~~
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

INFO:     127.0.0.1:8566 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     127.0.0.1:8566 - "GET /queue/data?session_hash=pow5vauo96 HTTP/1.1" 200 OK
INFO:     127.0.0.1:8566 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     127.0.0.1:8566 - "GET /queue/data?session_hash=pow5vauo96 HTTP/1.1" 200 OK

**Comment by YanWenKun** [comment]
@caomyv @STAR-FALL-00 
原因可能是 CUDA Toolkit 需要新版本，安装最新的 12.8.1 试试看：

https://developer.nvidia.com/cuda-12-8-1-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_network

注意只需要安装  [Libraries 与 Compilers](https://github.com/YanWenKun/Comfy3D-WinPortable/raw/refs/heads/main/docs/cuda-toolkit-install-selection.webp) 。

**Comment by YanWenKun** [comment]
@caomyv @STAR-FALL-00 @songnan1111 

用最新版试试看吧：

https://github.com/YanWenKun/Hunyuan3D-2-WinPortable/releases/tag/v3.1

新的 PyTorch 2.7 很好适配了 50 系显卡，稳定版也解决了编译时的诸多细节问题

**Comment by YanWenKun** [comment]
憋了个新版出来，现在有 GUI 启动器了，并且升级到了 CUDA 12.9，试试看吧：
https://github.com/YanWenKun/Hunyuan3D-2-WinPortable/blob/main/README.zh.adoc
